# Generated by Django 5.2.3 on 2025-07-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_planotreino'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanoTreino',
        ),
    ]
